# GitHub Actions workflow to deploy a static site to GitHub Pages.
#
# What it does:
# 1. Triggers on push to the `main` branch.
# 2. Checks out the repository code.
# 3. Checks if the version in package.json has changed.
# 4. If changed, sets up Node.js 20.
# 5. Installs project dependencies.
# 6. Builds the static site into the `dist` directory.
# 7. Pushes the contents of `dist` to the `gh-pages` branch.
#
# Important notes:
# - GitHub does NOT automatically configure the Pages source when deployed using GitHub Actions.
# - After the first deployment, you must configure GitHub Pages manually:
#
#   1. Go to your repository on GitHub.
#   2. Click on the "Settings" tab.
#   3. Scroll down to the "Pages" section in the sidebar.
#   4. Under "Source", choose:
#        - Branch: `gh-pages`
#        - Folder: `/ (root)`
#   5. Click "Save".
#
# - Once this is done, future deployments will update the site automatically.

name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Check version change
              id: version_check
              run: |
                  if git rev-parse HEAD~1 >/dev/null 2>&1; then
                    if git diff HEAD~1 HEAD -- package.json | grep -E '"version":'; then
                      echo "version_changed=true" >> $GITHUB_ENV
                    else
                      echo "version_changed=false" >> $GITHUB_ENV
                    fi
                  else
                    echo "First commit detected. Proceeding with deployment."
                    echo "version_changed=true" >> $GITHUB_ENV
                  fi

            - name: Exit if no version change
              if: env.version_changed == 'false'
              run: echo "No version change detected. Skipping deployment." && exit 0

            - name: Set up Node.js
              if: env.version_changed == 'true'
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              if: env.version_changed == 'true'
              run: npm install

            - name: Build
              if: env.version_changed == 'true'
              run: npm run build
              env:
                  PUBLIC_URL: /${{ github.event.repository.name }}

            - name: Deploy to gh-pages
              if: env.version_changed == 'true'
              run: |
                  cd dist
                  git init
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"

                  git add .
                  git commit -m "Deploy to gh-pages"

                  git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

                  git push --force origin HEAD:gh-pages
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
